"""
Bibliography formatters for BibTeX and formatted citations.

Generates:
- references.bib (for LaTeX)
- Formatted citation lists (for Word and text)
"""

from typing import List, Dict, Any
from .parser import ZoteroItem
from .index import CitationIndex


class BibTeXFormatter:
    """Generate BibTeX bibliography files."""
    
    @staticmethod
    def generate(items: List[ZoteroItem], include_header: bool = True) -> str:
        """
        Generate complete BibTeX file content.
        
        Args:
            items: List of ZoteroItem objects
            include_header: Include standard BibTeX header comment
            
        Returns:
            BibTeX file content
        """
        lines = []
        
        if include_header:
            lines.append("% Generated by RAG Research Assistant")
            lines.append("% Zotero Bibliography Export")
            lines.append("")
        
        for item in items:
            lines.append(item.to_bibtex())
            lines.append("")
        
        return '\n'.join(lines)
    
    @staticmethod
    def generate_from_citekeys(index: CitationIndex, citekeys: List[str]) -> str:
        """
        Generate BibTeX from list of citekeys.
        
        Args:
            index: CitationIndex instance
            citekeys: List of citekeys to include
            
        Returns:
            BibTeX content
        """
        items = []
        for citekey in citekeys:
            item = index.get(citekey)
            if item:
                items.append(item)
        
        return BibTeXFormatter.generate(items)


class FormattedCitationFormatter:
    """Generate human-readable citations in various formats."""
    
    # IEEE numeric style formatter
    @staticmethod
    def format_ieee_numeric(items: List[ZoteroItem], start_index: int = 1) -> str:
        """
        Format citations in IEEE numeric style.
        
        Example:
            [1] J. Doe and A. Smith, "Title of paper," Journal Name, vol. 10, 2023.
            [2] ...
        
        Args:
            items: List of ZoteroItem objects
            start_index: Starting number for citations
            
        Returns:
            Formatted bibliography string
        """
        lines = []
        
        for i, item in enumerate(items, start=start_index):
            authors = BibTeXFormatter._format_authors_short(item.authors)
            
            # Build citation string
            parts = [f"[{i}]", authors + ","]
            
            if item.title:
                parts.append(f'"{item.title},"')
            
            if item.journal:
                parts.append(f"in {item.journal},")
            
            if item.volume:
                parts.append(f"vol. {item.volume},")
            
            if item.year:
                parts.append(f"{item.year}.")
            elif item.doi:
                parts.append(f"https://doi.org/{item.doi}")
            elif item.url:
                parts.append(item.url)
            else:
                parts.append("n.d.")
            
            lines.append(' '.join(parts))
        
        return '\n'.join(lines)
    
    @staticmethod
    def format_apa_style(items: List[ZoteroItem]) -> str:
        """
        Format citations in APA style.
        
        Example:
            Doe, J., & Smith, A. (2023). Title of paper. Journal Name, 10(2), 45-67.
        
        Args:
            items: List of ZoteroItem objects
            
        Returns:
            Formatted bibliography string
        """
        lines = []
        
        for item in items:
            parts = []
            
            # Authors
            if item.authors:
                authors = BibTeXFormatter._format_authors_apa(item.authors)
                parts.append(authors)
            else:
                parts.append("Unknown Author")
            
            # Year
            if item.year:
                parts.append(f"({item.year}).")
            else:
                parts.append("(n.d.).")
            
            # Title
            if item.title:
                parts.append(f"{item.title}.")
            
            # Publication
            if item.journal:
                parts.append(f"*{item.journal}*")
                if item.volume:
                    parts[-1] += f", {item.volume}"
                if item.issue:
                    parts[-1] += f"({item.issue})"
                if item.pages:
                    parts[-1] += f", {item.pages}."
                else:
                    parts[-1] += "."
            
            # DOI or URL
            if item.doi:
                parts.append(f"https://doi.org/{item.doi}")
            elif item.url:
                parts.append(item.url)
            
            lines.append(' '.join(parts))
        
        return '\n'.join(lines)
    
    @staticmethod
    def format_html_list(items: List[ZoteroItem], start_index: int = 1) -> str:
        """
        Format citations as HTML list.
        
        Args:
            items: List of ZoteroItem objects
            start_index: Starting number
            
        Returns:
            HTML list string
        """
        lines = ['<ol>']
        
        for i, item in enumerate(items, start=start_index):
            authors = BibTeXFormatter._format_authors_short(item.authors)
            title = item.title or "Unknown"
            year = item.year or 'n.d.'
            
            citation = f"{authors}, \"{title},\" {year}."
            lines.append(f"  <li>{citation}</li>")
        
        lines.append('</ol>')
        
        return '\n'.join(lines)
    
    @staticmethod
    def format_markdown_list(items: List[ZoteroItem]) -> str:
        """
        Format citations as Markdown list.
        
        Args:
            items: List of ZoteroItem objects
            
        Returns:
            Markdown list string
        """
        lines = []
        
        for i, item in enumerate(items, 1):
            authors = BibTeXFormatter._format_authors_short(item.authors)
            title = item.title or "Unknown"
            year = item.year or 'n.d.'
            
            citation = f"{authors}, \"{title},\" {year}."
            lines.append(f"{i}. {citation}")
        
        return '\n'.join(lines)


class BibTeXFormatter:
    """Utility methods for BibTeX formatting."""
    
    @staticmethod
    def _format_authors_short(authors: List[str], max_authors: int = 3) -> str:
        """
        Format authors in short form (et al. for long lists).
        
        Args:
            authors: List of author names
            max_authors: Maximum authors to show before "et al."
            
        Returns:
            Formatted author string
        """
        if not authors:
            return "Unknown"
        
        if len(authors) <= max_authors:
            return ' and '.join(authors)
        else:
            return f"{authors[0]} et al."
    
    @staticmethod
    def _format_authors_apa(authors: List[str]) -> str:
        """
        Format authors in APA style (et al. after first author).
        
        Args:
            authors: List of author names
            
        Returns:
            APA-formatted author string
        """
        if not authors:
            return "Unknown"
        
        if len(authors) == 1:
            return authors[0]
        elif len(authors) == 2:
            return f"{authors[0]} & {authors[1]}"
        else:
            return f"{authors[0]} et al."