"""
Format paper drafts as LaTeX (IEEEtran) with references.bib.
"""

from typing import List, Dict, Any, Tuple
from pathlib import Path
from .engine import DraftedSection
from .outline import PaperOutline
from rag_assistant.zotero import BibTeXFormatter


class LaTeXFormatter:
    """Generate LaTeX files for drafted papers."""
    
    PREAMBLE = r"""\documentclass[conference]{IEEEtran}
\IEEEoverridecommandlockouts

\usepackage{cite}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{algorithmic}
\usepackage{graphicx}
\usepackage{textcomp}
\usepackage{xcolor}

\def\BibTeX{{\rm B\kern-.05em{\sc i\kern-.025em b}\kern-.08em
    T\kern-.1667em\lower.7ex\hbox{E}\kern-.125emX}}

\begin{document}

\title{%s}

\author{\IEEEauthorblockN{Author Name}
\IEEEauthorblockA{\textit{Your Institution} \\
City, Country \\
email@example.com}
}

\maketitle

\begin{abstract}
%s
\end{abstract}

\begin{IEEEkeywords}
keyword1, keyword2, keyword3
\end{IEEEkeywords}

"""
    
    CONCLUSION = r"""

\section*{Acknowledgments}
This research was conducted using the RAG Research Assistant, a local-first citation management system.

\bibliographystyle{plain}
\bibliography{references}

\end{document}
"""
    
    @staticmethod
    def format_paper(outline: PaperOutline, sections: List[DraftedSection],
                    citations: List[Dict[str, Any]]) -> Tuple[str, str]:
        """
        Generate LaTeX main.tex and references.bib.
        
        Args:
            outline: PaperOutline with structure
            sections: List of DraftedSection objects
            citations: List of citation dicts
            
        Returns:
            Tuple of (main_tex_content, references_bib_content)
        """
        # Generate main.tex
        abstract = outline.abstract or "This paper presents research on " + outline.title
        
        latex_content = LaTeXFormatter.PREAMBLE % (
            LaTeXFormatter._escape_latex(outline.title),
            LaTeXFormatter._escape_latex(abstract)
        )
        
        # Add sections
        for section in sections:
            latex_content += LaTeXFormatter._format_section(section)
        
        latex_content += LaTeXFormatter.CONCLUSION
        
        # Generate references.bib from citations
        bibtex_content = LaTeXFormatter._generate_bibtex(citations)
        
        return latex_content, bibtex_content
    
    @staticmethod
    def _format_section(section: DraftedSection) -> str:
        """Format a single section."""
        heading = r"\section" if section.level == 1 else r"\subsection"
        
        # Escape LaTeX special characters
        title = LaTeXFormatter._escape_latex(section.title)
        content = LaTeXFormatter._escape_latex(section.content)
        
        return f"\n{heading}{{{title}}}\n{content}\n"
    
    @staticmethod
    def _escape_latex(text: str) -> str:
        """Escape special LaTeX characters."""
        replacements = {
            '&': r'\&',
            '%': r'\%',
            '$': r'\$',
            '#': r'\#',
            '_': r'\_',
            '{': r'\{',
            '}': r'\}',
            '~': r'\textasciitilde{}',
            '^': r'\textasciicircum{}',
        }
        result = text
        for char, escape in replacements.items():
            result = result.replace(char, escape)
        return result
    
    @staticmethod
    def _generate_bibtex(citations: List[Dict[str, Any]]) -> str:
        """Generate BibTeX from citations."""
        lines = [
            "% Generated by RAG Research Assistant",
            "% Paper references with automatic citations",
            ""
        ]
        
        for i, citation in enumerate(citations, 1):
            # Create minimal BibTeX entry from citation metadata
            source = citation.get('source_path', 'unknown')
            page = citation.get('page_or_section', 'section')
            
            lines.append(f"@misc{{cite{i},")
            lines.append(f"  author = {{RAG System}},")
            lines.append(f"  title = {{{page}}},")
            lines.append(f"  note = {{From {source}}}")
            lines.append("}")
            lines.append("")
        
        return '\n'.join(lines)
    
    @staticmethod
    def save_to_files(outline: PaperOutline, sections: List[DraftedSection],
                     citations: List[Dict[str, Any]], output_dir: str):
        """
        Save LaTeX files to directory.
        
        Args:
            outline: PaperOutline
            sections: List of DraftedSection
            citations: List of citations
            output_dir: Output directory path
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        main_tex, references_bib = LaTeXFormatter.format_paper(
            outline, sections, citations
        )
        
        # Save main.tex
        (output_path / 'main.tex').write_text(main_tex)
        
        # Save references.bib
        (output_path / 'references.bib').write_text(references_bib)
        
        return {
            'main_tex': str(output_path / 'main.tex'),
            'references_bib': str(output_path / 'references.bib')
        }